"""
Single source of truth for constants shared between the Python build tools and C source.

Python files import directly from this module.
Run as a script to generate c/constants.h for the C compiler.

Usage:
    python python/constants.py c/constants.h
"""

import argparse
from pathlib import Path

# ---------------------------------------------------------------------------
# Screen layout
# ---------------------------------------------------------------------------
SCREEN_WIDTH = 32
SCREEN_HEIGHT = 16
PIXEL_WIDTH = SCREEN_WIDTH * 2    # 64
PIXEL_HEIGHT = SCREEN_HEIGHT * 3  # 48
TOTAL_CHARS = SCREEN_WIDTH * SCREEN_HEIGHT  # 512

# ---------------------------------------------------------------------------
# Slideshow timing
# ---------------------------------------------------------------------------
PAN_STEPS = 8
PAN_DELAY = 15    # delay iterations between pan steps
HOLD_DELAY = 40   # delay iterations to hold the final frame
STATIC_DELAY = (PAN_STEPS + 1) * PAN_DELAY  # total delay for non-panning images


def write_header(path: Path) -> None:
    """Write c/constants.h containing all absolute screen and timing constants."""
    with open(path, "w") as f:
        f.write("/* Auto-generated by python/constants.py -- do not edit by hand */\n\n")
        f.write("#ifndef CONSTANTS_H\n")
        f.write("#define CONSTANTS_H\n\n")
        f.write(f"#define SCREEN_WIDTH  {SCREEN_WIDTH}\n")
        f.write(f"#define SCREEN_HEIGHT {SCREEN_HEIGHT}\n\n")
        f.write(f"#define PAN_STEPS    {PAN_STEPS}\n")
        f.write(f"#define PAN_DELAY    {PAN_DELAY}\n")
        f.write(f"#define HOLD_DELAY   {HOLD_DELAY}\n")
        f.write( "#define STATIC_DELAY ((PAN_STEPS + 1) * PAN_DELAY)\n\n")
        f.write("#endif /* CONSTANTS_H */\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate c/constants.h from the shared constants module."
    )
    parser.add_argument("output", metavar="OUTPUT", help="path for the output header file")
    args = parser.parse_args()
    write_header(Path(args.output))
    print(f"Generated {args.output}")
